[tool.poetry]
name = "rpcs"
version = "0.1.0"
description = ""
authors = ["Karan Kadakia <kkadakia@thebulldoggroupllc.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
